BuildHabits/urls.py
from django.urls import path

from . import views

app_name = "buildhabits"
urlpatterns = [
	path('', views.index, name='index'),
	path('login/', views.login_user, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('register/', views.register, name='register'),
	path('homepage/', views.homepage, name='homepage'),
	path('addhabit/', views.addHabit, name='addhabit'),
	path('viewhabits/', views.viewHabits.as_view(), name='viewhabits'),
	path('<int:pk>/', views.habitDetails.as_view(), name='habitdetails'),
	path('viewtoday/', views.viewToday, name='viewtoday'),
	path('<int:pk>/edit/', views.editHabitDetails.as_view(), name='edithabitdetails'),
]

MyDjangoProjects/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
	path('buildhabits/', include('BuildHabits.urls')),
	path('admin/', admin.site.urls),
]

BuildHabits/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

def getTodaysDate():
	return timezone.localtime(timezone.now()).replace(hour=0,minute=0,second=0,microsecond=0)
	
class Habit(models.Model):
	habit_text = models.CharField(max_length=50)
	belongs_to = models.CharField(max_length=150)
	date_added = models.DateTimeField("date added")
	# the occurrence is the number of days between when each habit should appear on the list
	occurrence = models.IntegerField()
	last_modified = models.DateTimeField("date habit was last changed", default=getTodaysDate())

	def __str__(self):
		return self.habit_text


class TodayHabitList(models.Model):
	habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
	username = models.CharField(max_length=150)
	track_date = models.DateTimeField("date habit is performed")
	completed = models.BooleanField(default=False)

	def is_completed(self):
		return self.completed

BuildHabits/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Habit, TodayHabitList
from django.views import generic

# Create your views here.

def index(request):
	return render(request, 'BuildHabits/index.html')

def login_user(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('buildhabits:homepage'))

	if request.method == "GET":
		return render(request, 'BuildHabits/login.html')
	elif request.method == "POST":
		try:
			username = request.POST['username']
			password = request.POST['password']
		except KeyError:
			return render(request, 'BuildHabits/login.html',{'error_message':'You must fill in the fields'})
		else:
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return HttpResponseRedirect(reverse('buildhabits:homepage'))
			else:
				return render(request, 'BuildHabits/login.html', {'error_message':'Invalid login'})

def logout_user(request):
	logout(request)
	return HttpResponseRedirect(reverse('buildhabits:index'))

def register(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('buildhabits:homepage'))

	if request.method == "GET":
		return render(request, 'BuildHabits/register.html')
	elif request.method == "POST":
		try:
			username = request.POST['username']
			email = request.POST['email']
			password = request.POST['password']
		except KeyError:
			return render(request, 'BuildHabits/register.html', {'error_message':'You must fill in all the fields'})

		user = User.objects.create_user(username,email,password)
		user.save()
		return HttpResponseRedirect(reverse('buildhabits:homepage'))

def homepage(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('buildhabits:login'))

	return render(request, 'BuildHabits/homepage.html')

def addHabit(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('buildhabits:login'))

	if request.method == "GET":
		return render(request, 'BuildHabits/addhabit.html')
	elif request.method == "POST":
		try:
			newHabit = Habit(belongs_to=request.user.get_username(), habit_text=request.POST['activity'], occurrence=request.POST['occurrence'], date_added=timezone.localtime(getTodaysDate()))
		except KeyError:
			return render(request, 'BuildHabits/addhabit.html',{'error_message':'There was an error, please fill in the form'})
		else:
			newHabit.save()
			return HttpResponseRedirect(reverse('buildhabits:homepage'))

class viewHabits(generic.ListView):

	template_name = 'BuildHabits/viewhabits.html'
	context_object_name = 'allHabits'

	def get(self, request):
		if not request.user.is_authenticated:
			return HttpResponseRedirect(reverse('buildhabits:login'))

		query = self.my_get_queryset(request)
		return render(request, 'BuildHabits/viewhabits.html', {'allHabits':query})

	def my_get_queryset(self, request):
		queryset = Habit.objects.filter(belongs_to=request.user)
		return queryset.order_by('-date_added')

class habitDetails(generic.DetailView):
	model = Habit
	template_name = 'BuildHabits/habitdetails.html'

	def get(self, request, pk):
		if not request.user.is_authenticated:
			return HttpResponseRedirect(reverse('buildhabits:login'))
		
		habit = get_object_or_404(Habit,pk=pk)
		if request.user.get_username() != habit.belongs_to:
			habit = None

		return render(request, 'BuildHabits/habitdetails.html', {'habit':habit})

def check_if_habit_daily_habit_exists(today, habit, todayshabits):
	for h in todayshabits:
		if habit.habit_text == h.habit.habit_text:
			return True

	return False

def convert_queryset_to_list(checkhabits):
	todayshabits = []
	for i in checkhabits:
		todayshabits.append(i)

	return todayshabits

def viewToday(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('buildhabits:login'))

	today = getTodaysDate()
	checkhabits = TodayHabitList.objects.filter(username=request.user.get_username()).filter(track_date=today)
	if(request.method == "GET"):
		todayshabits=convert_queryset_to_list(checkhabits)
		habits = Habit.objects.filter(belongs_to=request.user.get_username())
		for currHabit in habits:
			habit_date = currHabit.date_added
			if((habit_date-today).days % currHabit.occurrence == 0):
				if not check_if_habit_daily_habit_exists(today, currHabit, todayshabits):
					newHabitToday = TodayHabitList.objects.create(username=currHabit.belongs_to,habit_id=currHabit.id,track_date=today, completed=False)
					# Line 50: Trying to create a database entry into the TodayHabitList table with the parent's id from Habit table
					todayshabits.append(newHabitToday)

		return render(request,'BuildHabits/viewtoday.html', {'todayshabits':todayshabits})

	elif(request.method == "POST"):
		checkboxTicked = request.POST.getlist('checkbox')
		for i in checkhabits:
			if str(i.id) in checkboxTicked:
				i.completed = True
			else:
				i.completed = False
			i.save()

		return HttpResponseRedirect(reverse('buildhabits:viewtoday'))

# A method to get the current date with time set to 0
def getTodaysDate():
	return timezone.localtime(timezone.now()).replace(hour=0, minute=0, second=0, microsecond=0)

class editHabitDetails(generic.DetailView):

	model = Habit
	template_name = 'BuildHabits/edithabitdetails.html'

	def get(self, request, pk):
		if not request.user.is_authenticated:
			return HttpResponseRedirect(reverse('buildhabits:login'))
		
		return render(request, 'BuildHabits/edithabitdetails.html')

	def post(self, request, pk):
		habit = get_object_or_404(Habit,pk=pk)
		habit_name = request.POST['updatedname']
		occurrence = request.POST['updatedoccurrence']
		updated = False
		if habit.habit_text != habit_name:
			habit.habit_text = habit_name
			updated = True
		if habit.occurrence != occurrence:
			habit.occurrence = occurrence
			updated = True

		if updated:
			habit.last_modified = getTodaysDate()
			habit.save()

		return HttpResponseRedirect(reverse('buildhabits:habitdetails', args=(pk,)))

BuildHabits/templates/BuildHabits/addhabit.html
<a href="{% url 'buildhabits:homepage' %}">Homepage</a>

{% if error_message %}
	<p style="color:red">{{error_message}}</p>
{% endif %}

<h1>Add a new habit</h1>
<form method="post">
	{% csrf_token %}
	<label>Enter the name of the activity</label>
	<br><input name="activity" type="text"></input>

	<br>
	<br><label>How often do you want to perform this activity?</label>
	<br><label><input type="radio" name="occurrence" value="1"></input>Daily</label>
	<br><label><input type="radio" name="occurrence" value="2"></input>Every other day</label>
	<br><label><input type="radio" name="occurrence" value="8"></input>Weekly</label>
	<br>

	<br><button action="submit">Add this habit</button>
	

</form>

BuildHabits/templates/BuildHabits/edithabitdetails.html
{% if habit %}
	<form method="post">
		{% csrf_token %}
		<h1> Editing {{ habit.habit_text }} </h1>
		<label>Change the name</label> <input name="updatedname" type="text" value="{{ habit.habit_text }}"></input>
		<br>
		<label>Change the occurrence</label> <input name="updatedoccurrence" type="text" value="{{ habit.occurrence }}"></input>
		<br><br>
		<button type="submit">Save</button>
	</form>
{% else %}
	<h3>The habit does not exist</h3>
{% endif %}

BuildHabits/templates/BuildHabits/habitdetails.html
<a href="{% url 'buildhabits:viewhabits' %}">View all habits</a>

{% if habit %}
	<h2> Details for {{ habit.habit_text }}</h2>
	<h3> Added on {{ habit.date_added }}</h3>
	<h3> Occurs every {{ habit.occurrence }}</h3>

	<a href="{% url 'buildhabits:edithabitdetails' habit.id %}">Edit this habit</a>
{% else %}
	<p> This habit does not exist </p>
{% endif %}

BuildHabits/templates/BuildHabits/homepage.html
<p><a href="{% url 'buildhabits:viewhabits' %}">View all your habits</a></p>
<p><a href="{% url 'buildhabits:addhabit' %}">Add a new habit</a></p>
<p><a href="{% url 'buildhabits:viewtoday' %}">View your habits for Today</a></p>
<br>
<p><a href="{% url 'buildhabits:logout' %}">Logout</a></p>

BuildHabits/templates/BuildHabits/index.html
<a href="{% url 'buildhabits:login' %}">Login</a>
<br>
<a href="{% url 'buildhabits:register' %}">Register</a>

BuildHabits/templates/BuildHabits/login.html
<h1>Login</h1>

{% if error_message %}
	<p style="color:red">{{ error_message }}</p>
{% endif %}

<form method='POST'>
	{% csrf_token %}
	<input name="username" type="text" placeholder="Username"></input>
	<br>	
	<input name="password" type="password" placeholder="Password"></input>
	<br><br>
	<button type="submit">Login</button>
</form>

<a href="{% url 'buildhabits:register' %}" style="font-size:10px">Create an account<a>

BuildHabits/templates/BuildHabits/register.html
<h1>Register</h1>

{% if error_message %}
	<p style="color:red">{{ error_message }}</p>
{% endif %}
<form method='POST'>
	{% csrf_token %}
	<input name="username" type="text" placeholder="username"></input>
	<br>
	<input name="email" type="email" placeholder="email"></input>
	<br>
	<input name="password" type="password" placeholder="password"></input>
	<br><br>
	
	<button type="submit">Register</button>

</form>

<a href="{% url 'buildhabits:login'  %}" style="font-size:10px">Login</a>

BuildHabits/templates/BuildHabits/viewhabits.html
<a href="{% url 'buildhabits:homepage' %}">Homepage</a>

{% if allHabits %}
	<ul>
	{% for habit in allHabits %}
		<li><a href="{% url 'buildhabits:habitdetails' habit.id %}">{{ habit.habit_text }}</a></li>	
	{% endfor %}
	</ul>
{% else %}
	<p> You didn't enter any habits <p>

{% endif %}

BuildHabits/templates/BuildHabits/viewtoday.html
<a href="{% url 'buildhabits:homepage' %}">Homepage</a>

<h1>Today's activities list</h1>

{% if todayshabits %}
    <form method="POST">
        {% csrf_token %}
        <ul>
            {% for i in todayshabits%}
            <label><input type="checkbox" name="checkbox" value={{i.id}} {% if i.completed %} checked {% endif %}>{{ i.habit.habit_text }}</input></label><br>
            {% endfor %}
        </ul>

        <button type="submit">Save List</button>
    </form>
{% else %}
    <p>There are no habits for Today</p>
{% endif %}